### ISSUE TITLE
Can I use a LCD screen with the PT2257?

### ISSUE THREAD

**Issue by gigi199596** [victornpb/Evc_pt2257#1]
Hello,

I'm using a LCD screen on pins A4 and A5.
Is it possible to get conflicts when pins for the pt2257 are set on A0 and A1?

Because if I only use Pt2257, there's no problem but if I add a LCD screen with i2c bus, the LCD is going well but PT2257 seems to be off...

Is there a solution to use the 2 at the same time?

thanks a lot

Gilles

**Comment by victornpb** [comment]
It depends on how yout lcd library is using the i2c, i2c is supposed so support multiple devices in parallel, but you need to make sure both libraries are not trying to use the serial port on the same time in different ways. The pt2257 uses a software serial port, you can try moving then other pins.

**Comment by gigi199596** [comment]
@ok thanks for the answer :) I tried to change the pins and it's still not working. 

But why did you put the PT2257 address as 0x88 (in the .cpp file)? Because when I use the i2c scanner, I got my LCD and the PT2257 detected (on A4 and A5):
- LCD screen is on 0x27
- PT2257 is on 0x44.

Do I need to change address 0x88 with 0x44?

**Comment by gigi199596** [comment]
no idea? :'(

**Comment by victornpb** [comment]
On page 4 of the datasheet http://www.princeton.com.tw/Portals/0/Product/PT2257.pdf
A Chip Address byte=88H
B10001000

You may have a chip with a different address.

**Comment by gigi199596** [comment]
It doesn't solve my problem :S I can use only one PT2257 device on the serial bus...
I'm gonna use a classic wiring for the LCD screen and put the PT2257 on the serial line

Thanks for your answers
