### ISSUE TITLE
Compiling Issue would be glad if you can Help me.

### ISSUE THREAD

**Issue by twixl** [victornpb/Evc_pt2257#2]
Hello,
I´m relativly new in the World of Arduino. But i want to build a Speaker wit the PT2257 and your libary. And I have a Problem with it. I use Win10Pro and Arduino 1.6.11. I Downloaded your libary installed it and tried to run the Example Code, but I always get a Error that there is something wrong with compiling (exit status 1) I tried to delete the Libary and install it again but it didn´t helped either. It would be glad if you can help me. Thanks
Greetings
Niklas

Here is my full Error Code:

Arduino: 1.6.11 (Windows 10), Board: "Arduino/Genuino Uno"

`ass_i2c_wait_scl_high' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_wait_scl_high' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_wait_scl_high' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_wait_scl_high' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

`ass_i2c_delay_half' referenced in section`.text' of C:\Users\Niklas\AppData\Local\Temp\ccw6G28T.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Evc_pt2257-master\Evc_pt2257.cpp.o (symbol from plugin)

collect2.exe: error: ld returned 1 exit status

exit status 1
Fehler beim Kompilieren für das Board Arduino/Genuino Uno.

**Comment by victornpb** [comment]
Someone commented this in one of my [instructables](http://www.instructables.com/id/Remote-Volume-Control-for-old-stereo-amp/):

> This does not compile in Arduino IDE 1.6.11. You need Arduino IDE 1.6.9 (gcc-4.8.1) or lower, to compile this. It fails on SoftI2CMaster current version. Even if you fix the compiler errors by changing 2x ((noinline)) to ((used,noinline)), it hangs the arduino.

I haven't touched this code since then, I don't know whats changed on the Arduino IDE.
